version: "3.9"

services:
  auth:
    build:
      context: ./auth-service
    container_name: iot-auth
    command: ["9001"]
    ports:
      - "9001:9001"
    networks:
      - iot_net

  server:
    build:
      context: ./server
    container_name: iot-server
    depends_on:
      - auth
    environment:
      AUTH_HOST: auth
      AUTH_PORT: "9001"
      HTTP_PORT: "8080"
      HTTP_WEB_ROOT: "/app/web"
    command: ["9000", "/app/logs/server.log"]
    ports:
      - "9000:9000"
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge
